var pubilc=new Vuex.Store({
    state:{
        userName:'',
        userPhoto:'',
        alertShow:false,
        tipsContent:'',
        certain:'确定',
        delWhat:{},
        moveOrEnd:true,
        editShow:false,
        editWhat:{},
        isEdit:null,
        addWhat:{name:'',actor:'',director:'',type:'',time:'',area:''},
        search:{name:'',actor:'',director:'',type:'',time:'',area:''},
    },
    getters:{},
    mutations:{},
    actions:{}
})