var play=Vue.extend({
    template:'#play',
    data:function(){
        return{
            movieName:'',
            reviewUse:false,
            userReview:{content:''},
            url:'http://localhost:18080/user/',
            allReview:[],
            user:'',
            isManager:false,
            newReview:{movie:'',user:'',content:'',time:''}
        }
    },
    created:function(){
        this.movieName=decodeURI(location.search.match(/\?([\s\S]*)/)[1]);
        this.newReview.movie=this.movieName;
        if(localStorage.length!==0){
            this.reviewUse=true
        };
        this.user=localStorage.userName;
        this.newReview.user=this.user;
        this.isManager=localStorage.isManager;
        this.getReview();
    },
    methods:{
        getReview:function(){
            axios({
                url:this.url+'getReview',
                method:'get',
            }).then(function(result){
                result.data.reverse();
                this.allReview=result.data
            }.bind(this)).catch(function(err){
                console.log(err)
            })
        },
        del:function(data){
            axios({
                url:this.url+'delReview',
                method:'get',
                params:data
            }).then(function(result){
                if(result.data=='删除成功'){
                    this.getReview();
                }
            }.bind(this)).catch(function(err){
                console.log(err)
            })
        },
        addReview:function(){
            var data=this.newReview;
            var d=new Date();
            data.time=d.getFullYear()+'年'+(d.getMonth()+1)+'月'+d.getDate()+'日'+d.toLocaleTimeString();
            axios({
                url:this.url+'addReview',
                method:'get',
                params:data
            }).then(function(result){
                if(result.data=='发表成功'){
                    this.newReview={movie:'',user:'',content:'',time:''};
                    this.getReview();
                }
            }.bind(this)).catch(function(err){
                console.log(err)
            })
        }
    }
})
Vue.component('play',play)